// Declaration of kernel functions.
#pragma kernel ClearGrid
#pragma kernel UpdateCellOccupancy
#pragma kernel CalculateOffsets
#pragma kernel SumOffsets
#pragma kernel FinalizeOffsets
#pragma kernel ReArrangeBoids

#define THREAD_GROUP_SIZE 1024

#include "Assets/Junheng/Shaders/Compute/BoidSimulationData.hlsl"
#include "Assets/Junheng/Shaders/Compute/GPU_Grid_Spatial_Partition/SpatialPartitionUtils.hlsl"

// Buffer containing the number of boids located in the cell, for each cell in the grid.
RWStructuredBuffer<uint> _CellOccupancyBuffer;
int _BoidsCount;

// For each cell in the grid, the function resets the number of boids in the cell.
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void ClearGrid (uint cellIndex : SV_DispatchThreadID)
{
    if((int)cellIndex >= _TotalCellCount) {
        return;
    }

    // Set the current number of boids in this cell to 0.
    _CellOccupancyBuffer[cellIndex] = 0;
}

// Buffer containing information for each boid about the index of the cell it belongs to and the order in that cell (0-indexed).
RWStructuredBuffer<BoidCellInfo> _BoidsCellInfoBuffer;
// Buffer containing initial information about boids.
StructuredBuffer<BoidInfo> _Boids;

// For each boid, the function calculates the ID of the cell it belongs to. Also, it updates the increases the total number of boids
// in that cell by 1 and stores the order of the boid for that cell (0-based). 
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void UpdateCellOccupancy (uint boidIndex : SV_DispatchThreadID)
{
    if((int)boidIndex >= _BoidsCount) {
        return;
    }

    // Calculate the cell ID for the boid, based on its world position.
    // This ID represents the cell that the boid belongs to inside the parition grid.
    BoidInfo boidInfo = _Boids[boidIndex];
    uint cellID = GetCellID(boidInfo.position);

    // Update the index of the cell for the boid.
    _BoidsCellInfoBuffer[boidIndex].CellID = cellID;

    // Increase the number of boids in this cell, and store the previous number of boids in the cell
    // as the current order index of the boid in this cell (0-based).
    InterlockedAdd(_CellOccupancyBuffer[cellID], 1, _BoidsCellInfoBuffer[boidIndex].OrderInsideCell);
}

// Buffer containing boid offsets for each cell. Basically it contains the index of the first boid of the cell after this one.
RWStructuredBuffer<uint> _CellsOffsetsBuffer;
// Buffer containing the offsets for each thread group, used to update the boid offsets on a global level, since 
// they're initially calculated for each thread group locally. We need two of them since we're going to ping-pong
// values between them in the Sum Offsets kernel.
RWStructuredBuffer<uint> _ThreadGroupsGlobalOffsetsBuffer;
StructuredBuffer<uint> _ThreadGroupsGlobalOffsetsHelperBuffer;

// Temporary array shared between all threads inside one thread group. It holds the temporary result
// during the prefix-sum algorithm execution. It's twice the size of the thread group since we're
// going to use it as a double buffer for ping-ponging the results between the first and sceond half 
// of the array during the algorithm.
groupshared int helperArray[THREAD_GROUP_SIZE * 2];

// For each cell, calculate the prefix-sum of boids. This way, we can calculate the index of boids 
// inside each cell by computing the total sum of boids located in cells before it.
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void CalculateOffsets (uint globalThreadIndex : SV_DispatchThreadID, uint localThreadIndexInGroup : SV_GroupThreadID, uint threadGroupIndex : SV_GroupID)
{
    // Indices that we use to switch between the place in the helper array from which we
    // read and to which we write data. Classic buffer ping-pong technique.
    int dataInputIndex = THREAD_GROUP_SIZE;
    int dataOutputIndex = 0;

    // First, each thread stores the number of boids in the cell into a helper array. If the thread index is 
    // larger than the total number of cells in the grid, set the number of boids in that cell to 0.
    helperArray[localThreadIndexInGroup] = globalThreadIndex >= (uint)_TotalCellCount ? 0 : _CellOccupancyBuffer[globalThreadIndex];
    // We need to wait for every thread to do this before we can continue.
    GroupMemoryBarrierWithGroupSync();

    // Running the prefix-sum algorithm on the helper array. The result will be a filled helper array where
    // each element contains the sum of all elements before it added to the initial number of elements inside it.
    // For example, let's say that we have cells with corresponding amount of boids inside: [1, 0, 3, 2, 1, 5, 0, 1]
    // After running the algorithm, the resulting part of the helper array (that contains the final data) will 
    // have these values [1, 1, 4, 6, 7, 12, 12, 13].
    [unroll]
    for(uint completedCellsCount = 1; completedCellsCount < THREAD_GROUP_SIZE; completedCellsCount *= 2) 
    {
        // Update the input/output multipliers to switch the place where we read and where we write the data.
        dataOutputIndex = THREAD_GROUP_SIZE - dataOutputIndex;
        dataInputIndex = THREAD_GROUP_SIZE - dataOutputIndex;

        if(localThreadIndexInGroup < completedCellsCount) 
        {
            // For cells we've already completed the prefix-sum algorithm, 
            // just copy the data from the input part of the buffer to the output part.
            helperArray[dataOutputIndex + localThreadIndexInGroup] = helperArray[dataInputIndex + localThreadIndexInGroup];
        } 
        else 
        {
            // For uncompleted cells, update the total sum of boids before this cell. Note that the completed cells count is used as an offset
            // to get the appropriate data each iteration.
            helperArray[dataOutputIndex + localThreadIndexInGroup] = helperArray[dataInputIndex + localThreadIndexInGroup] + helperArray[dataInputIndex + localThreadIndexInGroup - completedCellsCount];
        }

        // We need to wait for every thread to finish this iteration before we continue with the algorithm.
        GroupMemoryBarrierWithGroupSync();
    }

    // Making sure we don't try to write the data outside the buffer scope.
    if(globalThreadIndex >= (uint)_TotalCellCount) 
    {
        return;
    }

    // After the prefix-sum algorithm is completed, write the prefix-sum of each cell into an output buffer.
    _CellsOffsetsBuffer[globalThreadIndex] = helperArray[dataOutputIndex + localThreadIndexInGroup];

    // The first thread in the group also writes to the buffer containing the total amount of boids in each thread group.
    // This buffer will be used to sort the offsets globally later on, since currently all offsets are local to the thread group.
    if(localThreadIndexInGroup == 0) 
    {
        // The total sum for this thread group is contained inside the last element.
        _ThreadGroupsGlobalOffsetsBuffer[threadGroupIndex] = helperArray[dataOutputIndex + THREAD_GROUP_SIZE - 1];
    }
}

// Variables used only by the Sum Offsets kernel.
int _TotalThreadGroupsCount;
int _CompletedTreadGroupsCount;

// For each thread group block, this function sums the global offset using the prefix-sum algorithm.
// The result will be a correct global offset for each thread group, that can then be used by the 
// finalize offsets kernel to apply it to each cell.
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void SumOffsets (uint threadGroupIndex : SV_DispatchThreadID)
{
    if(threadGroupIndex >= (uint)_TotalThreadGroupsCount) 
    {
        return;
    }

    if(threadGroupIndex < (uint)_CompletedTreadGroupsCount) 
    {
        // Completed thread groups offsets should just be copied over to the destination buffer.
        _ThreadGroupsGlobalOffsetsBuffer[threadGroupIndex] = _ThreadGroupsGlobalOffsetsHelperBuffer[threadGroupIndex];
    } 
    else 
    {
        // Uncompleted thread groups offsets need to be summed with the groups before them. After each iteration, the _CompletedThreadGroupsCount is doubled.
        _ThreadGroupsGlobalOffsetsBuffer[threadGroupIndex] = _ThreadGroupsGlobalOffsetsHelperBuffer[threadGroupIndex] + _ThreadGroupsGlobalOffsetsHelperBuffer[threadGroupIndex - _CompletedTreadGroupsCount];
    }
}

// For each cell, the function updates their local offsets based on the global offsets of each group
// they belong, resulting the correct global offsets of each cell.
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void FinalizeOffsets (uint globalThreadIndex : SV_DispatchThreadID, uint threadGroupIndex : SV_GroupID)
{
    // The first thread group don't need to add any offsets since its the first one. Also,
    // if the index of the thread exceeds the total cells count, return.
    if(threadGroupIndex == 0 || globalThreadIndex >= (uint)_TotalCellCount) 
    {
        return;
    }

    // Update the offset of each cell based on the global offset of the group it belongs.
    // This results in the correct global offset of each cell. Using the helper buffer to hold the input data since
    // we don't have it declared as read/write which will make it more optimized.
    _CellsOffsetsBuffer[globalThreadIndex] += _ThreadGroupsGlobalOffsetsHelperBuffer[threadGroupIndex - 1];
}

// Buffer containing the boids information, sorted based on their location in the partition grid.
RWStructuredBuffer<BoidInfo> _SortedBoids;

// For each boid, function re-arranges its index based on the cell it belongs and its order in that cell.
// This results in an array of boids that are neatly alligned in the memory for a faster access when executing
// boid simulation on the GPU.
[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void ReArrangeBoids (uint boidIndex : SV_DispatchThreadID)
{
    if(boidIndex >= (uint)_BoidsCount) 
    {
        return;
    }

    // Get the boid cell info for this boid (their index match).
    BoidCellInfo boidCellInfo = _BoidsCellInfoBuffer[boidIndex];
    // The final index of the boid in the sorted array is equal to the global offset of the cell it belongs
    // to, subtracted by the order of the boid inside that cell. We subtract one to get the 0-based index.
    uint sortedBoidIndex = _CellsOffsetsBuffer[boidCellInfo.CellID] - boidCellInfo.OrderInsideCell - 1;
    _SortedBoids[sortedBoidIndex] = _Boids[boidIndex];
}